language: scala

scala:
   - 2.11.8
   - 2.12.0

jdk:
   - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test &&
    sbt ++"2.11.8" clean coverage test coverageReport &&
    sbt ++"2.11.8" coverageAggregate


after_success:
  - sbt ++"2.11.8" coveralls